version: '3.1'

services:
  node-mongo-api:
    image: node-mongo-api:1.0.0
    container_name: node-mongo-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/home/api
      - ./node_modules:/home/api/node_modules
    networks:
      - mongo-db-network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoapitest
    networks:
      - mongo-db-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoapitest
      ME_CONFIG_MONGODB_URL: mongodb://root:mongoapitest@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mongo-db-network

networks:
  mongo-db-network:
    driver: bridge
